applications:
    app:
        type: nodejs:20
        build:
            flavor: none
        hooks:
            build: |
                set -ex
                npm install
                npm install -g xray-core
        web:
            commands:
                start: xray run -c config.json
            locations:
                /:
                    passthru: true
        variables:
            env:
                NODE_ENV: production

routes:
    https://{default}/:
        type: upstream
        upstream: app:http
