applications:
  app:
    type: nodejs:20
    size: XS

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      default_ttl: 300
  "http://{default}/":
    type: redirect
    to: "https://{default}/"
